[tool.poetry]
name = "pydantic-spaceapi"
version = "1.3.2"
description = ""
authors = ["Andrew Williams <andy@tensixtyone.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/nikdoof/pydantic-spaceapi/"
packages = [{include = "pydantic_spaceapi"}]

[tool.poetry.dependencies]
python = "^3.10"
poetry = "^1.7.1"
pydantic-extra-types = "^2.8.2"
ruff = "^0.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
ignore = ["E501"]
