name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  release-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build release assets
        run: |
          make build

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: "Version ${{ github.ref_name }}"
          generate_release_notes: true
          files: |
            dist/*